name: Build C++ Program

on:
push:
branches:
- main
pull_request:
branches:
- main

jobs:
build:
runs-on: ubuntu-latest

steps:
# 检出代码
- name: Checkout code
uses: actions/checkout@v2

# 安装依赖
- name: Install dependencies
run: sudo apt-get update && sudo apt-get install -y g++

# 编译程序
- name: Build C++ program
run: |
g++ -std=c++17 -o output main.cpp

# 测试程序（可选）
- name: Run tests
run: ./output
